# list of users who can sent announcement to their allowed users
admins:
- user: '@xx:xxx.com'
  general:
  - '@xx:xxx.com'
  - '@xx:xxx.com'
  - '@xx:xxx.com'
- user: '@xx:xxx.com'
  general:
  - '@xx:xxx.com'
  - '@xx:xxx.com'
  - '@xx:xxx.com'
widget_url: 
    https://xxx.com/#/?theme=$org.matrix.msc2873.client_theme&matrix_user_id=$matrix_user_id&matrix_display_name=$matrix_display_name&matrix_avatar_url=$matrix_avatar_url&matrix_room_id=$matrix_room_id&matrix_client_id=$org.matrix.msc2873.client_id&matrix_client_language=$org.matrix.msc2873.client_language&matrix_base_url=$org.matrix.msc4039.matrix_base_url
